spring.application.name=shopIT

spring.datasource.url=jdbc:h2:file:./data/shopitdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.h2.console.enabled=true

spring.datasource.username=mk
spring.datasource.password=mk78
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

#spring.security.user.name=Manohar
#spring.security.user.password=manohar
